[wizard]
move_speed = 5

[game]
lives = 3
up_keys = ["W", "UP"]
down_keys = ["S", "DOWN"]

# used for cordoning off the top bar from the game area
min_play_area_height = 50

# pause in Millisecond after a fireball hits a monster
hit_pause = 100

[fireball]
move_speed = 7
fast_move_speed = 14
damage = 1
power_damage = 2

[powerup]
# in seconds
despawn_time = 2

[monster]
speed_multiplier = 2
power_heal = 1
pushback = 20
pushback_multiplier = 1.5